### PR TITLE
add AS::Duration#to_f

### PR DESCRIPTION
**Pull request by liukgg**
Add this method FOR something like 5.minutes.to_f, which is used in ActiveSupport::Cache::Entry#initialize.

reference: Rails-->activesupport/lib/active_support/duration.rb

### CODE REVIEW

**Comment by janko** [comment]
Thanks!

**Comment by janko** [comment]
I would actually prefer to just add a `#to_f` method instead. Are there anything more you wanted to tackle with `#method_missing`, or is adding `#to_f` ok?

**Comment by liukgg** [comment]
Actually, I just need a #to_f right now, it's good enough for me.
However, I suppose that maybe there is something esle like #to_f which is needed by Rails somewhere we don't know right now.And a #method_missing method is the solution from Rails's activesupport/lib/active_support/duration.rb.
After all, you can take a decision, and both are ok for me.
Thanks!

**Comment by liukgg** [comment]
If you still think that we just add a #to_f now,  I can update  my code, and that's ok.  Just let me know your final decision, thanks!

**Comment by janko** [comment]
Yeah, I would like to add only #to_f then.

**Comment by janko** [comment]
Thank you! I will release a new version shortly.

**Comment by liukgg** [comment]
@janko-m   I created this pull request and it was merged, but I am not one of the contributors. It seems strange..Do you know why?  😃

**Comment by janko** [comment]
@liukgg Wait, you didn't create this pull request?

**Comment by liukgg** [comment]
Ah ha？
This pull request was actually created by me. 
You can see from this: 
https://github.com/janko-m/as-duration/pulls?q=is%3Apr+author%3Aliukgg+is%3Aclosed

**Comment by janko** [comment]
What is strange then?

**Comment by liukgg** [comment]
It is strange that I am not one of the contributors of this project.
https://github.com/janko-m/as-duration/graphs/contributors

**Comment by janko** [comment]
@liukgg Oh, that's because the commits you pushed were authored with an email address that doesn't match the email address of your GitHub account, so GitHub doesn't do any linking.

```
commit 69c850326fcd52c83c519decf65628711f86b171 (liukgg/master, method_missing)
Author: kunliu <kun.liu@dji.com>
Date:   Fri Jun 24 00:11:08 2016 +0800

    add #to_f
```

**Comment by liukgg** [comment]
Oh, thank you! It's my fault that I used the wrong email address "kun.liu@dji.com".
Is there any way to change the author from "kunliu <kun.liu@dji.com>" to "liukgg<liuk1991@sina.com>" ?

**Comment by janko** [comment]
@liukgg No, it's not possible to change a commit author without changing the commit's SHA, which would change the history and would then require force-pushing to this repo's `master`.

**Comment by liukgg** [comment]
Ok, thank you very much for your reply and patience.

**Comment by liukgg** [comment]
One more question: what if I change my email address of my GitHub account  to "kun.liu@dji.com" ?

**Comment by janko** [comment]
@liukgg You can try, and then see if GitHub added your avatar and link to profile on the commit.

**Comment by liukgg** [comment]
😄  thanks

**Pull request merged**
